# CouplesBudget Pro Docker Compose
version: '3.8'

services:
  web:
    build: .
    ports:
      - "5000:5000"
    environment:
      - FLASK_CONFIG=production
      - DATABASE_URL=sqlite:///money_management.db
      - SECRET_KEY=your-secret-key-here
    volumes:
      - ./logs:/app/logs
      - ./instance:/app/instance
    depends_on:
      - redis
    
  redis:
    image: redis:7-alpine
    ports:
      - "6379:6379"
    
  nginx:
    image: nginx:alpine
    ports:
      - "80:80"
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf
    depends_on:
      - web
